stages:
  - build

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  cache: { }
  tags:
    - docker-executor
  image: registry.gitlab.stylers.ninja/stylers/sysops/ansible/ansible-management-service:latest
  script:
    - echo 'test'
